add: seismic to v1.1 for speed up and include annotated region at build time

diff --git a/intogen/seismic/Dockerfile b/intogen/seismic/Dockerfile
--- a/intogen/seismic/Dockerfile
+++ b/intogen/seismic/Dockerfile
@@ -15,12 +15,16 @@ RUN --mount=type=bind,target=/files \
     git config --global http.lowSpeedLimit 0 && \
     git config --global http.lowSpeedTime 999999 && \
     git config --global http.retry 5 && \
-    git clone --filter=blob:none https://github.com/larsson-lab/SEISMIC.git seismic && \
-    cd seismic && \
-    git checkout 688e9611c3047d214abd597ee6913b8e591e51c0 && \
+    git clone --filter=blob:none https://github.com/larsson-lab/SEISMIC.git /seismic && \
+    cp /files/seismic.patch /seismic.patch
+
+
+WORKDIR /seismic
+
+RUN git checkout 688e9611c3047d214abd597ee6913b8e591e51c0 && \
     git fetch --depth 1 && \
-    cp /files/seismic.patch / && \
-    git apply /seismic.patch
+    git apply /seismic.patch && \
+    git status
 
 
 FROM rocker/r-ver:4.1 AS final
@@ -32,6 +36,7 @@ ENV R_BASE_VERSION=4.1.3
 RUN apt-get update \
     && apt-get install -y --no-install-recommends --no-install-suggests \
         apt-utils \
+        curl \
         libcairo2-dev=1.16.0-4ubuntu1 \
         libcurl4-openssl-dev \
         libfontconfig1-dev=2.13.1-2ubuntu3 \
@@ -43,19 +48,34 @@ RUN apt-get update \
         libpng-dev=1.6.37-2 \
         libssl-dev \
         libtiff5-dev \
+        libwebp-dev \
         libxml2-dev \
         libxt-dev=1:1.1.5-1 \
         locales-all \
+        pkg-config \
         procps=2:3.3.16-1ubuntu2.4 \
         r-base-html=3.6.3-2 \
-        r-bioc-biostrings=2.54.0-1 \
-        r-bioc-genomicranges=1.38.0+dfsg-1 \
-        r-bioc-rsamtools=2.2.3-1 \
-        r-cran-ade4=1.7-15-1 \
-        r-cran-devtools=2.2.2-2 \
-        r-cran-seqinr=3.6-1-1 \
         r-doc-html=3.6.3-2 && \
     rm -rf /var/lib/apt/lists/*
+
+RUN install2.r --error --skipinstalled --ncpus -1 -r "https://cloud.r-project.org" -r getOption \
+    BiocManager \
+    cowplot \
+    R.utils \
+    textshaping \
+    ragg \
+    yaml \
+    tidyverse \
+    foreach \
+    doSNOW \
+    stringi \
+    inline \
+    Rcpp \
+    fitdistrplus \
+    data.table \
+    seqinr \
+    devtools \
+    ade4
 
 RUN --mount=type=bind,from=build,target=/build \
     Rscript /build/seismic/demo/install_R_dependencies.R && \
@@ -64,7 +84,27 @@ RUN --mount=type=bind,from=build,target=/build \
     cp -r /build/seismic/config /seismic/config && \ 
     cp /build/seismic/SEISMIC.R /seismic/SEISMIC.R
 
+RUN curl -fLO https://bioconductor.org/packages/release/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg19_1.4.3.tar.gz && \
+    R CMD INSTALL BSgenome.Hsapiens.UCSC.hg19_1.4.3.tar.gz && \
+    rm BSgenome.Hsapiens.UCSC.hg19_1.4.3.tar.gz
+
+RUN curl -fLO https://bioconductor.org/packages/3.14/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.4.tar.gz && \
+    R CMD INSTALL BSgenome.Hsapiens.UCSC.hg38_1.4.4.tar.gz && \
+    rm BSgenome.Hsapiens.UCSC.hg38_1.4.4.tar.gz
+
+
 RUN chmod -R a+rx /seismic/
+
+# This test is essential to store the annotated regions to speed up seismic runs
+RUN --mount=type=bind,from=build,target=/build \
+    cp /build/seismic/demo/TCGA_UCEC_SNVs.tsv /tmp/TCGA_UCEC_SNVs.tsv && \
+    Rscript /seismic/SEISMIC.R /seismic/config/config.yaml /tmp/TCGA_UCEC_SNVs.tsv UCEC WXS hg38 1 || true && \
+    rm /tmp/TCGA_UCEC_SNVs.tsv && \
+    if [ ! -f /tmp/regions_output.tsv ] || [ ! -s /tmp/regions_output.tsv ]; then \
+        echo "ERROR: Regions were not saved"; \
+        exit 1; \
+    fi
+
 
 LABEL version="0.1.1"
 LABEL description="SEISMIC: A tool for the analysis of somatic mutations in cancer adapted for IntOGen use."
